### ISSUE TITLE
Reasons for this fork

### ISSUE THREAD

**Issue by cocowalla** [ahydrax/Hangfire.PostgreSql#9]
Hi, as someone looking to use Postgres as a job store for Hangfire, I came across this repo and it's parent.

Unfortunately, I couldn't see anything in the readme that explains the reasons for the fork, or why I might want to use it instead of the parent?

**Comment by ahydrax** [comment]
Hi @cocowalla, 

Good point to have separate section in readme explaining why you may want to choose this package instead of parent.

In short, there are several points:
1. Queue implementation is bad in original project but compatible with old pgsql `(<9.6)` - my fork uses special syntax for queue introduced in `pgsql 9.6`;
2. Same for distributed locks;
3. Connectivity wasn't good enough - fully refactored here;
4. Job counters table can grow huge in original project - implemented counters aggregation here;
5. Currently I'm using my fork in production so I'm also interesting in stability/performance.

Also the performance is here: removed a lot of string concatenations, used proper data structures, optimized queries, etc.

**Comment by cocowalla** [comment]
Exactly what I wanted to know, thanks 👍
